var map_config = {
	'default':{
		'bordercolor':'#ffffff', //inter-state borders
		'lakescolor':'#88DBFF', //lakes color
		'shadowcolor':'#000000', //shadow color below the map
		'shadowOpacity':'100', //shadow opacity, value, 0-100
		'namescolor':'#ffffff', //color of the abbreviations 
		'namesShadowColor':'#000', //tooltip shadow color
	},
	'map_1':{
		'namesId':'AL',//name's ID (Don't change it)
		'name': 'ALABAMA',  //state name
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property', //Goto URL
		'target':'_blank', //open link in new window:_blank, open in current window:_self
		'upcolor':'#C7C7C7', //state's color when page loads
		'overcolor':'#2BBFFF', //state's color when mouse hover
		'downcolor':'#008C23',//state's color when mouse clicking
		'enable':true,//true/false to enable/disable this state
	},
	'map_2':{
		'namesId':'AK',
		'name': 'ALASKA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':false,
	},
	'map_3':{
		'namesId':'AZ',
		'name': 'ARIZONA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_4':{
		'namesId':'AR',
		'name': 'ARKANSAS',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_5':{
		'namesId':'CA',
		'name': 'CALIFORNIA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},	
	'map_6':{
		'namesId':'CO',
		'name': 'COLORADO',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_7':{
		'namesId':'CT',
		'name': 'CONNECTICUT',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_8':{
		'namesId':'DE',
		'name': 'DELAWARE',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},	
	'map_9':{
		'namesId':'FL',
		'name': 'FLORIDA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_10':{
		'namesId':'GA',
		'name': 'GEORGIA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_11':{
		'namesId':'HI',
		'name': 'HAWAII',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'transparent',
		'enable':false,
	},	
	'map_12':{
		'namesId':'ID',
		'name': 'IDAHO',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_13':{
		'namesId':'IL',
		'name': 'ILLINOIS',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_14':{
		'namesId':'IN',
		'name': 'INDIANA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_15':{
		'namesId':'IA',
		'name': 'IOWA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},	
	'map_16':{
		'namesId':'KS',
		'name': 'KANSAS',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_17':{
		'namesId':'KY',
		'name': 'KENTUCKY',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_18':{
		'namesId':'LA',
		'name': 'LOUISIANA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},	
	'map_19':{
		'namesId':'ME',
		'name': 'MAINE',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_20':{
		'namesId':'MD',
		'name': 'MARYLAND',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_21':{
		'namesId':'MA',
		'name': 'MASSACHUSETTS',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},	
	'map_22':{
		'namesId':'MI',
		'name': 'MICHIGAN',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_23':{
		'namesId':'MN',
		'name': 'MINNESOTA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_24':{
		'namesId':'MS',
		'name': 'MISSISSIPPI',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_25':{
		'namesId':'MO',
		'name': 'MISSOURI',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},	
	'map_26':{
		'namesId':'MT',
		'name': 'MONTANA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_27':{
		'namesId':'NE',
		'name': 'NEBRASKA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_28':{
		'namesId':'NV',
		'name': 'NEVADA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},	
	'map_29':{
		'namesId':'NH',
		'name': 'NEW HAMPSHIRE',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_30':{
		'namesId':'NJ',
		'name': 'NEW JERSEY',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#1F3F52',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_31':{
		'namesId':'NM',
		'name': 'NEW MEXICO',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},	
	'map_32':{
		'namesId':'NY',
		'name': 'NEW YORK',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#1F3F52',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_33':{
		'namesId':'NC',
		'name': 'NORTH CAROLINA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#1F3F52',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_34':{
		'namesId':'ND',
		'name': 'NORTH DAKOTA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_35':{
		'namesId':'OH',
		'name': 'OHIO',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#1F3F52',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},	
	'map_36':{
		'namesId':'OK',
		'name': 'OKLAHOMA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_37':{
		'namesId':'OR',
		'name': 'OREGON',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_38':{
		'namesId':'PA',
		'name': 'PENNSYLVANIA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#1F3F52',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},	
	'map_39':{
		'namesId':'RI',
		'name': 'RHODE ISLAND',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_40':{
		'namesId':'SC',
		'name': 'SOUTH CAROLINA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_41':{
		'namesId':'SD',
		'name': 'SOUTH DAKOTA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},	
	'map_42':{
		'namesId':'TN',
		'name': 'TENNESSEE',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_43':{
		'namesId':'TX',
		'name': 'TEXAS',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_44':{
		'namesId':'UT',
		'name': 'UTAH',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_45':{
		'namesId':'VT',
		'name': 'VERMONT',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},	
	'map_46':{
		'namesId':'VA',
		'name': 'VIRGINIA',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#1F3F52',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_47':{
		'namesId':'WA',
		'name': 'WASHINGTON',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':false,
	},
	'map_48':{
		'namesId':'WV',
		'name': 'WEST VIRGINIA',    
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},	
	'map_49':{
		'namesId':'WI',
		'name': 'WISCONSIN',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_50':{
		'namesId':'WY',
		'name': 'WYOMING',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
	'map_51':{
		'namesId':'DC',
		'name': 'WASHINGTON DC',
		'url':'http://netlz-demoserver.com/levin-25/index.php/demo-property',
		'target':'_blank',
		'upcolor':'#C7C7C7',
		'overcolor':'#2BBFFF',
		'downcolor':'#008C23',
		'enable':true,
	},
}
